version: "3.7"
services:
  # https://yaml.org/type/merge.html
  gst: &FULL
    image: docker-tegra-gst
    build:
      context: .
      dockerfile: Dockerfile
    command: /src/start.py
    # only for strace and debugging
    # security_opt:  
    #   - seccomp:unconfined
    # privileged: true
    devices:
      - /dev/nvhost-ctrl
      - /dev/nvhost-ctrl-isp
      - /dev/nvhost-ctrl-gpu
      - /dev/nvhost-prof-gpu
      - /dev/nvmap
      - /dev/nvhost-gpu
      - /dev/nvhost-as-gpu
      - /dev/nvhost-vic
      - /dev/nvhost-vi 
      - /dev/nvhost-isp
      - /dev/nvhost-tsec
      - /dev/nvhost-sched-gpu
      - /dev/tegra_dc_ctrl
      - /dev/tegra_dc_0
      - /dev/fb0
      - /dev/nvhost-msenc
      - /dev/nvhost-nvjpg
      - /dev/nvhost-nvdec
    volumes:
      - /usr/lib/aarch64-linux-gnu/tegra/:/usr/lib/aarch64-linux-gnu/tegra:ro
      - /usr/lib/aarch64-linux-gnu/tegra-egl:/usr/lib/aarch64-linux-gnu/tegra-egl:ro
      - /usr/local/cuda:/usr/local/cuda:ro
      - ./src:/src   
      - dbus:/tmp/dbus

    environment:
      - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda/lib64:/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra-egl
    depends_on:
      - dbus
  dbus:
    image: docker-tegra-dbus:latest
    init: true
    volumes:
      - dbus:/tmp/dbus

volumes:
  dbus: {}
