version: "3.7"
services:
  # https://yaml.org/type/merge.html
  gst: &FULL
    image: tegra-gst
    build:
      context: .
      dockerfile: Dockerfile
    command: /src/start.py
    devices:
      - /dev/nvhost-ctrl
      - /dev/nvhost-ctrl-gpu
      - /dev/nvhost-prof-gpu
      - /dev/nvmap
      - /dev/nvhost-gpu
      - /dev/nvhost-vic
      - /dev/nvhost-as-gpu
      - /dev/tegra_dc_ctrl
      - /dev/tegra_dc_0
      - /dev/fb0
    volumes:
      - /usr/lib/aarch64-linux-gnu/tegra/:/usr/lib/aarch64-linux-gnu/tegra:ro
      - /usr/lib/aarch64-linux-gnu/tegra-egl:/usr/lib/aarch64-linux-gnu/tegra-egl:ro
      - /usr/local/cuda:/usr/local/cuda:ro
      - ./src:/src   
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda/lib64:/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra-egl